Portfoliomodalpopup
stevenmukama/Microverseportfolio pull request #5
Opened 2022-11-18 15:17 UTC by stevenmukama

Added the portfolio modal popup 
Added  the CSS styles for styling the page

2022-11-18 15:22 UTC, anagudelogu reviewed
Hi @stevenmukama, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have the correct linter setup, please consider following steps by step this [guide](https://github.com/microverseinc/linters-config/tree/master/html-css-js).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-11-19 01:47 UTC, franclobo requested changes
Hi @stevenmukama, 

# Required Changes ♻️

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] ⚠️ Kindly review the announcements in the Slack channel they informed us about a change in the [README template](https://github.com/microverseinc/readme-template) IT IS GOING TO BE MANDATORY NEXT WEEK ⚠️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-19 01:47 UTC, franclobo commented on main.js
> +// }
- [ ] **[OPTIONAL]** Please 🙏🏽 remove the commented code to have a clean code that looks professional.

2022-11-19 01:47 UTC, franclobo commented on main.js
> +        </div>
- [ ] Please 🙏🏽 correct the path of the images, we could add a dot at the beginning `./images...` for a better user interface.

![image](https://user-images.githubusercontent.com/58642949/202827215-10e92eb5-52cc-493c-a33d-7c458d2cc8d2.png)

2022-11-19 01:47 UTC, franclobo commented on main.js
> +  },
- [ ] There are seven cards with the button `See project` you should have seven pop-up windows. Please 🙏🏽 add the pop-up window for a better user experience.

![image](https://user-images.githubusercontent.com/58642949/202827367-1f95943c-2975-47f5-8607-26cb499c6cc0.png)

2022-11-19 01:47 UTC, franclobo commented on style.css
> +  }
- [ ] For the desktop version of the pop-up window it is too close to the right border, kindly center the pop-up window to look similar to the Figma template.
- [ ] For the mobile version the pop-up window is too close to the borders, please 🙏🏽 center it to look similar to the Figma template.

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/202827782-cac021ed-5d80-47af-ae48-2f937f6bf34c.png) | ![image](https://user-images.githubusercontent.com/58642949/202827796-dd05f348-25d4-46d8-b1a5-3cb6304cd3cf.png) |
| ![image](https://user-images.githubusercontent.com/58642949/202827966-06d8d499-8f0c-4ed5-b500-12c18d351901.png) | ![image](https://user-images.githubusercontent.com/58642949/202827975-5be1f290-7e10-4f26-9c4f-d293123005fa.png) |

2022-11-19 01:47 UTC, franclobo commented on README copy.md
> +
- [ ] Kindly rename the file to `README.md` instead of `README copy.md` to do it possible to visualize on the repository. 👀 📑

2022-11-19 17:41 UTC, Santiago220991 approved these changes
Hi @stevenmukama, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
:heavy_check_mark: Applied changes suggested by the last reviewer.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Followed GitHub flow.

## Optional suggestions
[OPTIIONAL] Kindly make sure that your mobile version is showing all the pop-up content without horizontal and vertical scrolling. It helps to improve the user's experience. :+1: :smiley: :smiley: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-23 09:13 UTC, merged